.gitignore, web/templates/layout.gohtml
I had this lying around locally for a while. Very quick pr to add a select that lets you choose a country id and updates the query parameter. The data comes from an existing function and will change during another ticket. This pr is only a subset of the COR-502 ticket.
=> COR-502 Add country select frontend

cmd/mockData.go, cmd/mockdata/main.go, internal/db/individual.go
Added `country-id` and `count` options for the individual generator
Also, the `getInternal` method was logging way too much errors when uploading csvs
=> Individual generator upgrades

internal/api/individual.go, internal/api/individual_tabular.go, internal/api/individual_tabular_test.go, internal/constants/individual.go, internal/handlers/individual.go, internal/handlers/individuals_download.go, web/templates/individuals.gohtml
* Replace some strings with existing constants (from my previous pr)
* Remove country id from file upload/download
* Add Excel marshalling, with shared functionality for csv
* Add conditional excel/csv download to handler
* Update frontend to download via excel
=> COR-515 excel download

README.md
As I was working on the excel upload/download I touched a lot of code that is field specific.
I'm documenting the bits I've touched for when we tackle COR-505.
This is incomplete
=> Add some wip docs for changing the form's fields

web/templates/nav.gohtml, web/theme/theme.scss
noticed some issues, fixed them (button colors on certain states, card border radius, logo alignment, country selector dropdown)
=> COR-510: ui fixes

internal/api/individual.go, internal/handlers/index.go, web/templates/countries.gohtml, web/templates/country.gohtml, web/templates/country_select.gohtml, web/templates/individual.gohtml, web/templates/individuals.gohtml, web/templates/nav.gohtml, web/theme/theme.scss
=> COR-519: UX Fixes

cmd/serve.go, internal/server/middleware/auth.go, internal/server/middleware/auth_test.go, internal/server/middleware/countries.go, internal/server/middleware/ensure_selected_country.go, internal/server/middleware/has_country_permission.go, internal/server/middleware/has_global_admin_permission.go, internal/server/middleware/logging.go, internal/server/middleware/permissions.go, internal/server/middleware/permissions_test.go, internal/server/middleware/request_id.go, internal/server/middleware/selected_country.go, internal/server/options.go, internal/server/options_test.go, internal/server/routes.go, internal/server/server.go
Move middleware to a sub package and rename files/functions to remove the "middleware" prefix/suffix
=> Move middleware to a sub package

web/templates/countries.gohtml, web/templates/individuals.gohtml
setting the amount of items per page by setting the search parameter with a pagination-like button
also: when clicking on the country name, I link to the individuals page of that country now, when you want to edit it, you can click on the edit button. opinions?
=> COR-537: set amount of items per page

web/templates/individuals.gohtml
This looks bigger than it is due to some divs being removed and elements then beings unindented.
* Remove unnecessary divs
* Fix spacing of table and filters
* Fix table width to be same as filters width
* Align and reposition pagination controls
=> Table-alignment

internal/db/individual.go, internal/db/utils.go, internal/db/utils_test.go
Fixing the list individual batching logic. Adding some placeholder explanation for batch sorting.
=> Batch logic

internal/constants/individual.go, internal/handlers/individuals.go
Added constants representing the new fields for the individual. 
Some of the constants need deleting (Impairments). Will do once the individual is fully merged in. 
Renamed a few constants that were missing a "s" in the name. (`FormParam` vs `FormParams`)
=> COR-582 add constants for new fields

web/templates/individuals.gohtml, web/theme/theme.scss
chose a hybrid solution between option 1 and 2 in the ticket
table scrolls horizontally, first two columns are sticky (the select box, and the name column, cause it was the first one currently)
=> COR-535: make first two columns sticky and table scroll horizontally

web/templates/base.gohtml, web/theme/theme.scss
Adding the bold roboto font because it renders weirdly otherwise. Also added `sans-serif` fallback
=> Fix roboto font

web/templates/nav.gohtml, web/theme/theme.scss
implementing approximately the mock up designs for the country selection
=> COR-590: approximate mock up designs for country selection

web/templates/individuals.gohtml
Saves the horizontal scroll position of the table. Restores the position of the table when navigating to the page.
=> Restore table scroll position

web/templates/individual.gohtml
deletion of single individuals didn't work, because the button was disabled before submitting the form
=> COR-600: fix single individual deletion

cmd/mockdata/main.go, internal/api/individual.go, internal/api/individual_list_options.go, internal/api/individual_list_options_decoder.go, internal/api/individual_list_options_encoder.go, internal/api/individual_list_options_test.go, internal/api/individual_tabular.go, internal/api/validation/individual.go, internal/api/validation/individual_test.go, internal/constants/individual.go, internal/db/migrations.go, internal/db/migrations/postgres/017_add_office_field.up.sql, internal/db/sql_individual_list.go, internal/db/sql_individual_list_test.go, internal/views/individual_form.go, web/templates/individuals.gohtml, web/templates/nav.gohtml, web/templates/searchForm.gohtml
add an office field for data collection
=> COR-658: add office field

web/templates/countries.gohtml, web/templates/country.gohtml, web/templates/individual.gohtml, web/templates/individuals.gohtml, web/templates/nav.gohtml, web/theme/theme.scss
used flexbox for page layout
put the buttons in a fixed page footer
and the page headers in a fixed/sticky page header
only the main content scrolls now
also, only show search button when a country is selected
=> COR-575: table view

web/templates/base.gohtml, web/templates/country.gohtml, web/templates/individual.gohtml, web/templates/individuals.gohtml, web/templates/nav.gohtml, web/theme/theme.scss
=> COR-588: files menu

.~lock.generated.csv#, internal/api/individual_tabular.go, internal/api/individual_tabular_test.go, internal/api/utils.go
this is a tentative PR, since I find date validation to be quite unreliable, it sometimes works, sometimes not, I do not see a pattern.
everything else already works.
I would like to present the error in a nicer way, could do that in a different PR once I figure out how
=> COR-605: email validation, update error message

web/templates/individual.gohtml
the submission of the individual form was blocked by the disabled submit button
=> COR-664: first submit, then disable

.github/CODEOWNERS, OWNERS
add all of us as default owners for everything
=> add CODEOWNERS file

cmd/mockdata/main.go, cmd/template.go, internal/api/individual.go, internal/api/individual_tabular.go, internal/api/service_cc.go, internal/api/validation/const.go, internal/api/validation/individual.go, internal/constants/individual.go, internal/db/migrations.go, internal/db/migrations/postgres/023_add_service_fields.up.sql, internal/views/individual_form.go
Tests are failing upstream so I'll fix after merging
=> Add service fields

.~lock.generated.csv#, internal/api/disability_level.go, internal/api/displacement_status.go, internal/api/individual_tabular.go, internal/api/individual_tabular_test.go, internal/handlers/individuals_upload.go, internal/server/templates.go, web/templates/base.gohtml, web/templates/error.gohtml, web/templates/individuals.gohtml
show multiple errors, grouped by category
move error display to dedicated template
=> COR-675: displaying all errors at once

.idea/watcherTasks.xml, web/templates/individual.gohtml, web/templates/individuals.gohtml, web/templates/nav.gohtml, web/theme/theme.scss
added a cancel button on the individual form and a more explicit link back to the individuals list
took the opportunity to visually slim the navigation a bit, let me know what you think
=> COR-680: explicit list button & cancel button

internal/api/individual_tabular.go, internal/constants/countries.go, internal/constants/languages.go
looking up country names and language names when downloading and allowing iso codes as well as names for countries and languages when uploading
=> COR-681: iso values

web/templates/base.gohtml, web/templates/nav.gohtml
the sticky class on the header tag resulted in the upload modal not being in front of the backdrop
=> COR-737: move modal out of sticky header tag

internal/handlers/individuals_action.go, internal/handlers/individuals_upload.go, internal/server/routes.go
when validating the individuals for the action, we did not filter for country.
also properly rendering the errors now.
=> COR-739: filter for country, render errors

internal/views/individual_form.go
I took some liberties where it felt to make more sense
=> COR-732: fix form labels

internal/views/individual_form.go
this prevented the form from being submitted
=> COR-743: fix pwdComments field in form

internal/api/individual_list_options_decoder.go, internal/api/individual_list_options_encoder.go, internal/constants/individual.go, web/templates/individuals.gohtml
fixes COR-745 - the hidden sort icon by editing the offset of the sticky columns
fixes COR-746 - the broken download by adding the inactive property to the download link properly
fixes COR-731 - this one had already been merged but got lost due to an accidental force push on my part
=> COR-745/746/731

web/templates/searchForm.gohtml
just a suggestion, seems nicer to me
=> show "All" instead of nothing for search options

Makefile, cmd/serve.go, deploy/terraform/azurerm_linux_web_app.app.tf, internal/server/options.go, internal/server/options_test.go, internal/server/server.go, internal/server/templates.go, web/templates/nav.gohtml
we had talked about removing it in the past since it behaves weirdly and is unneccessary
=> COR-747: remove logout button

web/templates/nav.gohtml, web/theme/theme.scss
when we're on the participants page, mark that nav link as active
=> mark active nav link

deploy/terraform/azurerm_monitor_activity_log_alert.tf, deploy/terraform/azurerm_monitor_metric_alert.tf, deploy/terraform/azurerm_postgresql_flexible_server.postgres.tf
we have regular 401 errors, so we need to adjust the 4xx alert
=> add database health check, adjust 4xx alert, enable app health check

internal/db/healthz.go, internal/handlers/health.go, internal/server/routes.go, internal/server/server.go
* Add a log on successful health check (potentially removing this after debugging)
* Ping db connection when performing health check
=> Db health check

pkg/api/deduplication/deduplicationTypes.go
slighlty improving the way the deduplication types are displayed
=> COR-778: fix order of deduplication types

internal/api/individual_deduplication.go, internal/db/individual.go, internal/db/individual_test.go, internal/handlers/individuals_upload.go, pkg/api/deduplication/deduplicationTypes.go
should you find some issues with the deduplication, please check if they're birthdate specific. 
I found some unrelated issues, will create tickets for them
=> CPT-204: deduplicate on birthdate

README.md
Just updated the readme file with all the dependencies required when setting up a clean local environment.
=> fix(readme): added 3 missing dependencies to readme file

internal/db/individual.go, internal/db/individual_test.go
write nil values into temp table for empty ids in upload
=> CPT-699: enter null values in temp table for empty ids

README.md
Added few extra details to the README file.
=> fix(readme): Added details for generating css and test participants

internal/handlers/individuals_upload.go, web/templates/error.gohtml
conditionally add a download button to the error template, filled with a link that's built in the upload handler upon finding duplicates
=> CPT-704: download button for found duplicates

.github/pull_request_template.md
Jira ticket: No ticket, but it would look like this: JIRA-CPT-123
Created a PR template that looks like this.
Create a new PR, expect the sections to be there for me to fill.
None.
=> Added github PR template

internal/api/validation/individual.go
Jira ticket: JIRA-CORE24-157
* Remove validation rule for service comments
* Write a big comment
=> Core24 157 service comment field format

web/templates/countries.gohtml, web/templates/country.gohtml, web/templates/error.gohtml, web/templates/individual.gohtml, web/templates/individuals.gohtml, web/templates/support.gohtml, web/theme/theme.scss
=> Add support link
